import { Profile, Experience, Project, SkillCategory } from "./types";
import fadliPhoto from "./dli.59.28.jpeg";
import siperpustImg from "./assets/images/siperpust_showcase_1779405941977.png";
import couplealbumImg from "./assets/images/Couple Album Showcase.jpeg";
import absensiImg from "./assets/images/absensi_showcase.png";
import fastraImg from "./assets/images/fastracode.jpeg";

export const profileData: Profile = {
  name: "Fadli Kurniawan",
  title: "Sistem Informasi Student | Web & UI/UX Design",
  subTitle:
    "Menghadirkan perpaduan estetis antara Web & UI/UX Design, Landing Page Design, dan Mobile App Design untuk solusi digital yang interaktif dan komunikatif.",
  bio: "Mahasiswa Sistem Informasi yang memiliki minat dibidang Web Development dan UI/UX Design. Terbiasa merancang interface, membuat website responsive, serta menggunakan AI sebagai tools pendukung dalam proses desain dan pengembangan.",
  avatarUrl: fadliPhoto,
  location: "Jakarta Barat, Indonesia",
  email: "faadlikurniawan9@gmail.com",
  phone: "081285356113",
  resumePdfUrl: "#resume",
  education: [
    {
      program: "Sistem Informasi (S1)",
      institution: "Universitas Bina Sarana Informatika",
      period: "2024 - 2028",
    },
    {
      program: "Teknik Komputer Jaringan",
      institution: "SMK Telkom Jakarta",
      period: "2021 - 2023",
    },
  ],
  socials: {
    instagram: "https://www.instagram.com/dllikrnwn?igsh=MXJjcDd4NG1rc3FibA==",
    whatsapp: "https://wa.me/6281285356113",
    email: "mailto:faadlikurniawan9@gmail.com",
  },
};

export const experiencesData: Experience[] = [
  {
    id: "exp1",
    role: "FastraCode | Web Design & Development",
    company: "Project Pribadi",
    period: "Aktif",
    location: "Jakarta, Indonesia",
    description: [
      "Merancang UI/UX website menggunakan Figma dan Canva.",
      "Fokus pada responsive design, layout, dan user experience",
    ],
    skills: ["HTML", "CSS", "JavaScript", "Figma", "VSCode", "AI Tools"],
  },
  {
    id: "exp2",
    role: "Couple Album | Full-Stack Web Development",
    company: "Project Pribadi",
    period: "Aktif",
    location: "Jakarta, Indonesia",
    description: [
      "Mengembangkan aplikasi web gallery interaktif untuk menyimpan dan berbagi foto, video, serta catatan pribadi.",
      "Membangun sistem autentikasi pengguna menggunakan JWT dan bcrypt serta REST API untuk komunikasi frontend dan backend.",
      "Mengimplementasikan fitur upload media, email notification, scheduled tasks, dan download media dalam format zip.",
      "Melakukan deployment frontend dan backend menggunakan layanan cloud.",
    ],
    skills: [
      "React",
      "Vite",
      "TailwindCSS",
      "Framer Motion",
      "NodeJS",
      "ExpressJS",
      "MySQL",
      "JWT",
      "Cloudinary",
      "Nodemailer",
      "Vercel",
      "Render",
      "AI Tools",
    ],
  },
  {
    id: "exp3",
    role: "Mobile Attendance App | Full-Stack Mobile Application",
    company: "Project Pribadi",
    period: "Aktif",
    location: "Jakarta, Indonesia",
    description: [
      "Mengembangkan aplikasi absensi berbasis GPS dan foto menggunakan flutter dengan arsitektur state management Riverpod.",
      "Mengintregasikan REST API menggunakan Dio untuk komunikasi data antara aplikasi mobile dan backend.",
      "Mengimplementasikan fitur GPS, kamera, permission management, secure token storage, dan monitoring koneksi.",
      "Mengembangkan sistem push notification menggunakan Firebase Cloud Messaging dan local notification.",
    ],
    skills: [
      "Flutter",
      "Dart",
      "Riverpod",
      "Dio",
      "REST API",
      "Firebase",
      "Geolocator",
      "Image Picker",
      "Secure Storage",
      "AI Tools",
    ],
  },
  {
    id: "exp4",
    role: "SIPERPUST | Online Library Web",
    company: "Project Pribadi",
    period: "Aktif",
    location: "Jakarta, Indonesia",
    description: [
      "Mengembangkan perpustakan online berbasis web menggunakan laravel dan MySQL.",
      "Mengimplementasikan autentikasi API, manajemen data, export PDF/Excel, dan integrasi payment gateway.",
      "Membangun antarmuka responsif menggunakan TailwindCSS.",
    ],
    skills: [
      "PHP",
      "MySQL",
      "Sanctum",
      "TailwindCSS",
      "Midtrans",
      "DOMPDF",
      "Laravel",
      "Excel",
      "AI Tools",
    ],
  },
];

export const organizationsData: Experience[] = [
  {
    id: "exp1",
    role: "Wakil Ketua Himpunan Sistem Informasi (HIMSI)",
    company: "Universitas Bina Sarana Informatika",
    period: "2024 - Sekarang",
    location: "Jakarta, Indonesia",
    description: [
      "Membantu ketua dalam mengoordinasikan kegiatan dan memastikan program kerja HIMSI berjalan dengan baik dan terstruktur.",
      "Mengawasi kinerja divisi serta membantu menyelesaikan kendala dalam pelaksanaan kegiatan organisasi.",
      "Menjaga komunikasi dan kerja sama antar anggota untuk menciptakan lingkungan organisasi yang aktif, solid, dan bertanggung jawab.",
    ],
    skills: [
      "Kepemimpinan",
      "Manajemen Organisasi",
      "Komunikasi",
      "Koordinasi Acara",
      "Pemecahan Masalah",
    ],
  },
  {
    id: "exp2",
    role: "Humas Organisasi Kampus",
    company: "UKM Musik - Universitas Bina Sarana Informatika",
    period: "2025 - 2026",
    location: "Jakarta, Indonesia",
    description: [
      "Mengelola saluran komunikasi internal dan eksternal organisasi demi kelancaran koordinasi program kerja.",
      "Membantu penyebaran informasi kegiatan melalui pembuatan publikasi digital kreatif di media sosial dan platform digital.",
      "Bekerja sama secara aktif dalam tim lintas divisi untuk menyukseskan pelaksanaan kegiatan festival dan event organisasi.",
    ],
    skills: [
      "Humas",
      "Komunikasi Publik",
      "Media Sosial",
      "Desain Publikasi",
      "Kolaborasi Tim",
      "Manajemen Event",
    ],
  },
];

export const projectsData: Project[] = [
  {
    id: "proj1",
    title: "SIPERPUST - Online Library Web",
    category: "Web",
    summary:
      "Sistem informasi perpustakaan berbasis web yang dirancang untuk membantu proses digitalisasi pengelolaan data, layanan, dan aktivitas perpustakaan.",
    description:
      "SIPERPUST adalah sistem informasi perpustakaan berbasis web yang dikembangkan untuk mempermudah pengelolaan aktivitas perpustakaan secara digital. Sistem ini dirancang untuk membantu proses pengelolaan data koleksi, anggota, serta berbagai aktivitas administrasi dalam satu platform terintegrasi. Aplikasi dikembangkan menggunakan Laravel sebagai backend framework dengan MySQL sebagai database utama. Sistem juga mengimplementasikan autentikasi dan keamanan akses menggunakan Laravel Sanctum untuk mendukung pengelolaan pengguna dan akses berbasis API. Selain fitur manajemen data, SIPERPUST mendukung pembuatan laporan dan export data dalam format PDF serta Excel/CSV. Integrasi payment gateway Midtrans juga diterapkan untuk mendukung kebutuhan transaksi pembayaran dalam sistem. Pada sisi antarmuka, aplikasi menggunakan Tailwind CSS untuk membangun tampilan yang modern dan responsif. Proses pengembangan juga memanfaatkan Vite sebagai build tool serta Axios untuk mendukung komunikasi data antara frontend dan backend. ",
    technologies: [
      "Laravel",
      "PHP",
      "Laravel Sanctum",
      "MySQL",
      "TailwindCSS",
      "JavaScript",
      "Axios",
      "Vite",
      "Midtrans",
      "DOMPDF",
      "Laravel Excel",
      "Laragon",
      "Git/GitHub",
    ],
    liveUrl: "",
    imageUrl: siperpustImg,
    features: [
      "User authentication and authorization.",
      "Manajemen data buku dan kategori.",
      "Manajemen anggota perpustakaan.",
      "Peminjaman dan pengembalian buku.",
      "Pencarian dan pengelolaan koleksi.",
      "Export laporan PDF dan Excel/CSV.",
      "Payment gateway integration.",
      "Responsive web interface.",
    ],
  },
  {
    id: "proj2",
    title: "Mobile Attendance App | Full-Stack Mobile Application",
    category: "Mobile",
    summary:
      "Aplikasi absensi mobile yang dirancang untuk membantu proses pencatatan dan pengelolaan kehadiran karyawan secara digital menggunakan verifikasi lokasi GPS dan foto.",
    description:
      "Mobile Attendance App merupakan aplikasi absensi berbasis mobile yang dikembangkan untuk membantu proses pencatatan kehadiran karyawan secara lebih praktis, terstruktur, dan digital. Aplikasi memungkinkan pengguna melakukan proses check-in dan check-out dengan memanfaatkan lokasi GPS serta pengambilan foto sebagai bagian dari verifikasi kehadiran. Aplikasi dikembangkan menggunakan Flutter dan Dart dengan Riverpod sebagai state management untuk mengelola data dan kondisi aplikasi secara terstruktur. Komunikasi antara aplikasi mobile dan backend dilakukan melalui REST API menggunakan Dio sebagai HTTP client, sehingga data absensi dapat diproses dan dikelola secara terintegrasi. Berbagai fitur perangkat juga diintegrasikan ke dalam aplikasi, termasuk akses GPS menggunakan Geolocator, kamera dan galeri menggunakan Image Picker, serta Permission Handler untuk mengelola izin perangkat. Sistem juga menerapkan secure storage untuk menyimpan data autentikasi pengguna dengan lebih aman dan Shared Preferences untuk kebutuhan penyimpanan data lokal. Untuk meningkatkan pengalaman pengguna, aplikasi mendukung push notification melalui Firebase Cloud Messaging serta local notification untuk memberikan informasi dan pengingat terkait aktivitas absensi. Selain itu, aplikasi dilengkapi monitoring koneksi internet dan visualisasi data menggunakan grafik untuk membantu pengguna melihat informasi kehadiran. Antarmuka aplikasi dirancang dengan pendekatan modern dan responsif menggunakan berbagai elemen UI seperti custom font, SVG, dan animasi Lottie. Pengembangan aplikasi juga memperhatikan pengalaman pengguna agar proses absensi dapat dilakukan dengan mudah melalui perangkat mobile.",
    technologies: [
      "Flutter",
      "Dart",
      "Riverpord",
      "Dio",
      "REST API",
      "Geolocator",
      "Image Picker",
      "Permission Handler",
      "Firebase Cloud Messaging",
      "Flutter local notification",
      "Shared Preferences",
      "Flutter Secure Storage",
      "Google Fonts",
      "Flutter SVG",
      "Lottie",
      "FL Chart",
      "AI Tools",
    ],
    githubUrl: "",
    imageUrl: absensiImg,
    features: [
      "Absensi berbasis GPS & foto selfie dengan validasi lokasi dan pencatatan waktu otomatis real-time.",
      "Dashboard admin real-time dengan Live View kehadiran, rekap bulanan, dan manajemen payroll karyawan.",
      "Profil karyawan dengan dark mode, jadwal kerja, notifikasi push, dan pengajuan izin/cuti terintegrasi.",
    ],
  },
  {
    id: "proj3",
    title: "FastraCode | Web Design & Development",
    category: "Web",
    summary:
      "Platform wesbite yang menampilkan layanan desain UI/UX dan web development dengan tampilan modern, responsive, dan interaktif.",
    description:
      "Merancang dan mengembangkan website Fastra Code sebagai platform digital untuk memperkenalkan layanan UI/UX Design dan Web Development. Fokus utama pengembangan adalah menciptakan tampilan antarmuka yang modern, responsif, dan mudah digunakan. Proses desain mencakup perancangan layout, struktur halaman, responsive design, serta implementasi animasi untuk meningkatkan pengalaman pengguna. Dalam proses pengembangan, AI digunakan sebagai tools pendukung untuk membantu eksplorasi ide, perancangan desain, dan meningkatkan efisiensi proses development.",
    technologies: [
      "HTML",
      "CSS",
      "JavaScript",
      "Figma",
      "VSCode",
      "GitHub",
      "AI-Assisted Development Tools",
      "Vercel",
    ],
    liveUrl: "https://fastracode.vercel.app/",
    imageUrl: fastraImg,
    features: [
      "Responsive Design — Tampilan optimal untuk desktop, tablet, dan mobile",
      "Service Showcase — Menampilkan informasi layanan UI/UX Design dan Web Development.",
      "Portfolio Showcase — Menampilkan hasil dan informasi project.",
      "Interactive Animation — Animasi dan interaksi untuk meningkatkan user experience.",
      "Modern Landing Page — Struktur halaman yang dirancang untuk memperkenalkan layanan secara profesional.",
      "Contact Section — Memudahkan calon klien untuk menghubungi penyedia layanan.",
      "AI-Assisted Development — Pemanfaatan AI sebagai tools pendukung dalam proses desain dan development.",
    ],
  },
  {
    id: "proj4",
    title: "Couple Album | Full-Stack Web Development",
    category: "Web",
    summary:
      "Aplikasi web interaktif untuk pasangan yang memungkinkan pengguna menyimpan, mengelola, dan berbagi kenangan digital seperti foto, video, dan catatan dalam satu platform.",
    description:
      "Mengembangkan aplikasi web full-stack dengan frontend React dan backend Node.js untuk menyediakan platform penyimpanan kenangan digital bagi pasangan. Aplikasi dilengkapi sistem autentikasi menggunakan JWT, pengelolaan data melalui REST API, serta integrasi Cloudinary untuk upload dan penyimpanan media. Sistem juga mendukung pengiriman notifikasi email, scheduled task menggunakan node-cron, serta fitur download media dalam format ZIP. Frontend dirancang menggunakan React dan Tailwind CSS dengan animasi interaktif untuk memberikan pengalaman pengguna yang modern dan responsif.",
    technologies: [
      "React 19",
      "Vite",
      "Tailwind CSS",
      "Framer Motion",
      "Node.js",
      "Express.js",
      "MySQL",
      "JWT",
      "bcryptjs",
      "Multer",
      "Multer",
      "REST API",
      "Axios",
      "Nodemailer",
      "node-cron",
      "Archiver",
      "Vercel",
      "Render/Fly.io",
      "Git",
      "GitHub",
      "Laragon",
      "VS Code",
    ],
    liveUrl: "https://couple-album-3o23.vercel.app/",
    imageUrl: couplealbumImg,
    features: [
      "User Authentication — Registrasi, login, dan keamanan password menggunakan JWT dan bcrypt.",
      "Digital Album — Menyimpan dan mengelola foto serta video.",
      "Media Upload — Upload media dengan integrasi Cloudinary.",
      "Notes & Memories — Membuat dan mengelola catatan atau kenangan digital.",
      "Scheduled Notes — Catatan dapat dibuka pada waktu tertentu menggunakan scheduled task.",
      "Email Notification — Pengiriman notifikasi melalui email.",
      "Media Download — Download kumpulan media dalam format ZIP.",
      "Interactive UI — Animasi dan interaksi antarmuka menggunakan Framer Motion.",
      "Protected Routes — Pembatasan akses halaman berdasarkan status autentikasi.",
      "Responsive Design — Tampilan optimal untuk berbagai ukuran perangkat.",
    ],
  },
];

export const skillCategories: SkillCategory[] = [
  {
    id: "cat1",
    name: "Web & UI/UX",
    skills: [
      { name: "Desain Web (Figma)", level: 4.5 },
      { name: "Canva & Grafis", level: 4.5 },
      { name: "Landing Page Design", level: 4.8 },
      { name: "Responsive Design", level: 4.6 },
      { name: "Prototypinng", level: 4.7 },
      { name: "Wireframing", level: 3.5 },
    ],
  },
  {
    id: "cat2",
    name: "Web Development & Mobile",
    skills: [
      { name: "HTML", level: 4 },
      { name: "CSS", level: 4 },
      { name: "JavaScript", level: 3.5 },
      { name: "Laravel", level: 4 },
      { name: "Flutter/Dart", level: 3.8 },
      { name: "PHP", level: 3.9 },
      { name: "MySQL", level: 4.1 },
    ],
  },
  {
    id: "cat3",
    name: " Tools & AI",
    skills: [
      { name: "VSCode", level: 5 },
      { name: "Google AI Studio", level: 5 },
      { name: "Chat GPT", level: 5 },
      { name: "Gemini", level: 5 },
      { name: "Opencode", level: 5 },
      { name: "AI-Assisted Development", level: 4.9 },
    ],
  },
];
